name: dsc
version: 0.1.0
synopsis: Helper functions for setting up Double Submit Cookie defense for forms
description: See README at <https://github.com/qoelet/dsc#readme>
maintainer: Kenny Shen <kenny@machinesung.com>
license: MIT
github: qoelet/storeviva-login
category: Web

ghc-options: -Wall -Werror

dependencies:
  - base >= 4.7 && < 5
  - base64-bytestring
  - bytestring
  - SimpleAES
  - string-conversions

library:
  source-dirs: src
  exposed-modules:
    - Web.Csrf

tests:
  spec:
    cpp-options: -DTEST
    main: Spec.hs
    source-dirs:
      - test
      - src
    dependencies:
      - hspec == 2.*
      - QuickCheck
